### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by justyy** [tengge1/LOLModelViewer#1]
hi~。我看了你的lol-model-viewer。。。。真的很有意思。。。
我看了一下代码。里面模型的渲染还有动作的渲染都是viewer.js实现的么？？这个是作者自主研发的轮子？？其他地方想用可以直接套用么？？目前我这边想要实现在线预览3d max中的bip动作文件。不知道viewer.js支持否呢？

**Comment by tengge1** [comment]
你可以百度下`RiotFileTranslator`，用Maya从老版客户端里直接提取模型和动画。

**Comment by cksn** [comment]
请问 压缩包里文件怎么打开啊

**Comment by tengge1** [comment]
@cksn 哪里有压缩包？

**Comment by cksn** [comment]
> @cksn哪里有压缩包？

就是你放在那里的文件啊，我下载了，models文件夹里的文件不知道怎样打开，我想知道你说的那些模型要怎么使用，希望你能帮助我

**Comment by tengge1** [comment]
@cksn models里的文件是lolking自定义的模型格式，用软件打不开。只能用这个项目里的查看器查看，用我做的编辑器也能看：https://github.com/tengge1/ShadowEditor 。你可以给3dsmax或maya写个脚本导入。

**Comment by cksn** [comment]
很感谢你的解答，再次麻烦，请问如何给3dmax写脚本导入模型

**Comment by tengge1** [comment]
@cksn 不知道，没写过。建议用`RiotFileTranslator`转。

**Comment by cksn** [comment]
我在百度查的RiotFileTranslator.好像只能用maya2014版本的才可以对吗

**Comment by tengge1** [comment]
我只用过老的RiotFileTranslator，支持maya2012版本。
